### ISSUE TITLE
login doesn't work mongodb with replica set

### ISSUE THREAD

**Issue by israelidanny** [punkave/apostrophe#184] opened 2015-01-21 00:11 UTC
For some reason, login won't work if mysql is running in a replica set mode. 

On one of my projects I need an oplog to be able to sync with Elasticsearch, therefore I ran `mongod` in a 1-host replica set master kind of scenario.

If I do the following:
```
replSet=orthodox
oplogSize=1024
```

Nobody can't login to the site.

If I comment out the replica set settings, it all works.

**Comment by boutell** [comment] 2015-01-21 00:57
All we're doing is making simple queries against the aposPages collection.
My guess is your problem is something else. It is definitely not anything
we have any control over from our end; how could we?

On Tue, Jan 20, 2015 at 7:11 PM, Danny Povolotski <notifications@github.com>
wrote:

> For some reason, login won't work if mysql is running in a replica set
> mode.
>
> On one of my projects I need an oplog to be able to sync with
> Elasticsearch, therefore I ran mongod in a 1-host replica set master kind
> of scenario.
>
> If I do the following:
>
> replSet=orthodox
> oplogSize=1024
>
> Nobody can't login to the site.
>
> If I comment out the replica set settings, it all works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/184>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by israelidanny** [comment] 2015-01-21 00:59
The part with displaying pages works great. It's the login that doesn't work. It seems like it has something to do with sessions? How are you currently utilizing sessions in mongo? 

Again, give it a try on a machine you own. With replica sets and without. And you'll see that login doesn't work.

**Comment by boutell** [comment] 2015-01-21 01:00
The pages collection is also involved in login. Sessions are in a separate collection but still the same mongo database.

**Comment by boutell** [comment] 2015-01-21 01:04
We're handling sessions through appy, which reuses the same db connection for both sessions and the rest of the database. Still not seeing a way that can really go wrong... but you want to look around line 544 of appy.js.

Replica sets are not on our radar right now, I'd certainly accept a pull request on this though.

**Comment by israelidanny** [comment] 2015-01-21 01:06
Ok, I'll give it a look . Any educated guesses off the top of your head?

Again - behavior is as follows: 
- without replica set enabled, everything works great!
- with replica set, login does know when you entered good credentials, still redirects you to homepage, but it seems it immediately "forgets" you. No admin bar, nothing.

**Comment by boutell** [comment] 2015-01-21 13:56
My educated guess is that at the end of the day you'll be filing a bug
report on connect-mongo.

On Tue, Jan 20, 2015 at 8:06 PM, Danny Povolotski <notifications@github.com>
wrote:

> Ok, I'll give it a look . Any educated guesses off the top of your head?
>
> Again - behavior is as follows:
>
>    - without replica set enabled, everything works great!
>    - with replica set, login does know when you entered good credentials,
>    still redirects you to homepage, but it seems it immediately "forgets" you.
>    No admin bar, nothing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/184#issuecomment-70766815>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment] 2015-05-08 17:31
Hey, I've been learning more about mongodb and the way it guarantees you can read things after writing them (or rather, does not do that).

The default behavior with a replica set is that:

1. When you write, it is only confirmed that your write got to the primary node. There is no confirmation that it got to any others.
2. However, when you read, your reads always go to the current primary node too. So it ought to appear to work, although you don't get the performance benefit you probably expected.

What you're describing doesn't jibe with that, which is strange.

But I suspect your mongodb connection URL does not have the default parameters after all, and you're electing a combo that doesn't give you the kind of consistency you really need.

So it looks like for Apostrophe 0.5 at least (and 0.6, so far), the sensible use of replica sets is as a backup mechanism, not a load-scaling mechanism. But in future we could consider using different readPreference settings for critical and noncritical reads. Users who don't have sessions - they haven't done anything sticky yet - don't really need to have 100% up to date data returned to them. It can be a few milliseconds behind.

I am documenting the state of play and closing this ticket. It would make sense to open a new ticket at some point about better leveraging readPreference and writeConcern.

**Closed by boutell** 2015-05-08 17:31 UTC
Labels: backlog, incompatability, mongo
