### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ILLEGAL in $.extend(true, apos.data, { „mediaLibrary“: CONTENT })

### ISSUE THREAD

**Issue by matthaias** [punkave/apostrophe#397] opened 2016-01-05 10:13 UTC
Hi apostrophe-team,

we have some trouble with the script extending the apos.data object on the client side from https://github.com/punkave/apostrophe/blob/master/lib/push.js#L242.

The generated line in the browser extending the apos.data with the mediaLibrary information ($.extend(true, apos.data, { „mediaLibrary“: CONTENT })) throws an „Uncaught SyntaxError: Unexpected token ILLEGAL“ error in the browser. We can’t exactly specify what causes the error, as the CONTENT object is about 1.400.000 characters long (the object contains the blog page with all blogPost pages from the blog plugin).

CONTENT is similar to this:

```
{
  "mediaLibrary": {
    "aposPrefix": "",
    "doNotEdit": false,
    "offline": false,
    "demo": false,
    "loginButton": false,
    "siteTitle": "siteTitle",
    "shortName": "shortName",
    "hostName": "localhost:3000",
    "page": {
      "_id": "ID",
      "slug": "/",
      "path": "home",
      "title": "Home",
      "level": 0,
      "type": "blog",
      "published": true,
      "seoDescription": "",
      "tags": [],
      "orphan": false,
      "pagePermissions": ["edit-ID"],
      "andFromPagesIds": [],
      "andFromPagesRelationships": {},
      "sortTitle": "home",
      "highSearchText": "home",
      "highSearchWords": ["home"],
      "lowSearchText": "",
      "searchSummary": "",
      "blogWidget": {"slug": "/:blogWidget"...}  
      "_edit": true,
      "_publish": true,
      "url": "/",
      "ancestors": [],
      "peers": [
        {"_id": ID}
      ],
      "children": [...],                       
      "tabs": [...]
    }
  }
}
```

If we add an empty object to the mediaLibrary property the error won’t occur and everything works fine (it seems that other CMS functionalities won’t be affected). Is it a normal thing that the mediaLibrary property has so many data? Can we leave it blank or will this lead to another negative impact? Is it possible, that the "mediaLibrary" object contains unescaped characters?

Thanks in advance for your response!

**Comment by boutell** [comment] 2016-01-05 13:30
Hi Matthias,

I haven't seen this (the entire blog being pulled in by this). I checked it
in the standard sandbox when you first reported it. Do you have a test
project that reliably reproduces this that we could look at?

On Tue, Jan 5, 2016 at 5:13 AM, Matthias <notifications@github.com> wrote:

> Hi apostrophe-team,
>
> we have some trouble with the script extending the apos.data object on the
> client side from
> https://github.com/punkave/apostrophe/blob/master/lib/push.js#L242.
>
> The generated line in the browser extending the apos.data with the
> mediaLibrary information ($.extend(true, apos.data, { „mediaLibrary“:
> CONTENT })) throws an „Uncaught SyntaxError: Unexpected token ILLEGAL“
> error in the browser. We can’t exactly specify what causes the error, as
> the CONTENT object is about 1.400.000 characters long (the object contains
> the blog page with all blogPost pages from the blog plugin).
>
> CONTENT is similar to this:
>
> {
>   "mediaLibrary": {
>     "aposPrefix": "",
>     "doNotEdit": false,
>     "offline": false,
>     "demo": false,
>     "loginButton": false,
>     "siteTitle": "siteTitle",
>     "shortName": "shortName",
>     "hostName": "localhost:3000",
>     "page": {
>       "_id": "ID",
>       "slug": "/",
>       "path": "home",
>       "title": "Home",
>       "level": 0,
>       "type": "blog",
>       "published": true,
>       "seoDescription": "",
>       "tags": [],
>       "orphan": false,
>       "pagePermissions": ["edit-ID"],
>       "andFromPagesIds": [],
>       "andFromPagesRelationships": {},
>       "sortTitle": "home",
>       "highSearchText": "home",
>       "highSearchWords": ["home"],
>       "lowSearchText": "",
>       "searchSummary": "",
>       "blogWidget": {"slug": "/:blogWidget"...}
>       "_edit": true,
>       "_publish": true,
>       "url": "/",
>       "ancestors": [],
>       "peers": [
>         {"_id": ID}
>       ],
>       "children": [...],
>       "tabs": [...]
>     }
>   }
> }
>
> If we add an empty object to the mediaLibrary property the error won’t
> occur and everything works fine (it seems that other CMS functionalities
> won’t be affected). Is it a normal thing that the mediaLibrary property has
> so many data? Can we leave it blank or will this lead to another negative
> impact? Is it possible, that the "mediaLibrary" object contains unescaped
> characters?
>
> Thanks in advance for your response!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/397>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by matthaias** [comment] 2016-01-07 14:23
Hi @boutell,

thanks for your fast response! I think i have the problem now. After i read your answer i checked the error again and i saw that i get the position via firefox. It looks like we have some LINE SEPERATOR (<U+2028) characters in our database and JavaScript can't handle this, see http://stackoverflow.com/questions/2965293/javascript-parse-error-on-u2028-unicode-character

```
$.extend(true, {}, JSON.stringify({ "test": "first  last"}))
Uncaught SyntaxError: Unexpected token ILLEGAL(…)
```

Between first and last is this character and if i delete this in the database it works for this, but fails on the next one. 

Any idea to fix this?

**Comment by boutell** [comment] 2016-01-07 14:53
Yes, this is a legitimate concern I've bumped into once. We'll be looking
into a good canonical fix. Looks like escaping it with \u2028 is correct,
but I want to make sure we cover all the cases and also don't make it very
slow. It's strange that I haven't been able to quickly find a valid
implementation of this in npm. PHP's json_encode does the right thing by
default (and it's possible for it to be the "right thing" for everyone
because with the escapes, it's still valid JSON as well as valid JS).

On Thu, Jan 7, 2016 at 9:23 AM, Matthias <notifications@github.com> wrote:

> Hi @boutell <https://github.com/boutell>,
>
> thanks for your fast response! I think i have the problem now. After i
> read your answer i checked the error again and i saw that i get the
> position via firefox. It looks like we have some LINE SEPERATOR (<U+2028)
> characters in our database and JavaScript can't handle this, see
> http://stackoverflow.com/questions/2965293/javascript-parse-error-on-u2028-unicode-character
>
> $.extend(true, {}, JSON.stringify({ "test": "first  last"}))
> Uncaught SyntaxError: Unexpected token ILLEGAL(…)
>
> Between first and last is this character and if i delete this in the
> database it works for this, but fails on the next one.
>
> Any idea to fix this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/397#issuecomment-169677830>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by matthaias** [comment] 2016-01-07 15:22
Thanks a lot! 

> It's strange that I haven't been able to quickly find a valid
implementation of this in npm.

Yes, i was also searching. Looking forward to your fix!

**Comment by matthaias** [comment] 2016-02-10 09:23
@jth- Do you know, when will `Apostrophe 0.5` be released?

**Comment by boutell** [comment] 2016-02-10 14:07
0.5 has been out for quite some time (: I think you mean 0.6 which is
pending soon as we're finally doing an in-house project with it. But either
way we don't have a clean fix for this bug yet.

On Wed, Feb 10, 2016 at 4:23 AM, Matthias <notifications@github.com> wrote:

> @jth- <https://github.com/jth-> Do you know, when will Apostrophe 0.5 be
> released?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/397#issuecomment-182272672>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment] 2016-02-10 14:24
I'm having a bash at this now, the fix looks like it adds not much overhead
given that we already have similar fixes for things that would end the
script tag.

On Wed, Feb 10, 2016 at 9:07 AM, Tom Boutell <tom@punkave.com> wrote:

> 0.5 has been out for quite some time (: I think you mean 0.6 which is
> pending soon as we're finally doing an in-house project with it. But either
> way we don't have a clean fix for this bug yet.
>
> On Wed, Feb 10, 2016 at 4:23 AM, Matthias <notifications@github.com>
> wrote:
>
>> @jth- <https://github.com/jth-> Do you know, when will Apostrophe 0.5 be
>> released?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/punkave/apostrophe/issues/397#issuecomment-182272672>
>> .
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Closed** 2016-02-10 15:03 UTC
Labels: 0.5, bug, in progress

**Comment by boutell** [comment] 2016-02-10 16:06
Fix is published. I added one more commit in master to make the replace properly global.

**Comment by matthaias** [comment] 2016-02-11 14:19
Thank you very much! We will update our project soon to your latest release.
