### ISSUE TITLE
no image backend specified and neither imagecrunch nor identify found in PATH

### ISSUE THREAD

**Issue by 0vermind** [punkave/apostrophe#320] opened 2015-08-01 16:26 UTC
Installing on fedora 24 i get:

>apostrophe-site/index.js:678
        throw err;
              ^
>no image backend specified and neither imagecrunch nor identify found in PATH

I think you need a more automated install process otherwise to capture more people.

**Comment by boutell** [comment] 2015-08-01 17:33
Hi 0vermind,

That's a more general issue to be sure, one we might address when it makes
sense, but this message is not a bug. You need to install imagemagick. The
documentation covers that.

However I'll change that error message to say the 'imagemagick command line
tools "identify" and "convert"' so it's a little clearer what needs to
happen.


On Sat, Aug 1, 2015 at 12:26 PM, 0vermind <notifications@github.com> wrote:

> Installing on fedora 24 i get:
>
> apostrophe-site/index.js:678
> throw err;
> ^
> no image backend specified and neither imagecrunch nor identify found in
> PATH
>
> I think you need a more automated install process otherwise to capture
> more people.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/320>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment] 2015-08-01 17:36
(The change has been published to the uploadfs module.)

On Sat, Aug 1, 2015 at 1:33 PM, Tom Boutell <tom@punkave.com> wrote:

> Hi 0vermind,
>
> That's a more general issue to be sure, one we might address when it makes
> sense, but this message is not a bug. You need to install imagemagick. The
> documentation covers that.
>
> However I'll change that error message to say the 'imagemagick command
> line tools "identify" and "convert"' so it's a little clearer what needs to
> happen.
>
>
> On Sat, Aug 1, 2015 at 12:26 PM, 0vermind <notifications@github.com>
> wrote:
>
>> Installing on fedora 24 i get:
>>
>> apostrophe-site/index.js:678
>> throw err;
>> ^
>> no image backend specified and neither imagecrunch nor identify found in
>> PATH
>>
>> I think you need a more automated install process otherwise to capture
>> more people.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/punkave/apostrophe/issues/320>.
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by benirose** [comment] 2015-08-01 17:37
We agree. We're looking to review our errors that get reported when your environment isn't full configured or set up yet. Since we already have a ticket for that, Tom closed this. Thanks for putting a vote towards addressing these errors.

**Comment by benirose** [comment] 2015-08-01 17:49
Tom, can you include in the error "Do you have imagemagick or imagecrunch installed?" to make it super obvious?

**Comment by boutell** [comment] 2015-08-01 18:08
I put in this:

      no image backend specified and neither "imagecrunch" nor the
imagemagick utility "identify" found in PATH. Install imagemagick

I went with "install imagemagick" because imagecrunch is rather obscure and
most people aren't going to want to go find that little one-off of ours.

* * *

Some notes on the whole "one-click Apostrophe" discussion...

I built it two years ago as part of an effort toward a one-line install
command which worked, but was dropped because we really don't have a story
to tell around that idea. Every time we get into it we reach questions like:

"How would updates get installed later?"

"What happens next if you install Apostrophe with 'one click'? Are you then
dumped into the command-line world, or does it need a configuration UI like
Drupal? Who will build and maintain that?"

"Do we install xcode and homebrew for you? Can we even do the former? Or do
we provide a starter kit of pre-built set of binaries and tell you to move
to homebrew later if you are serious? How do people make that transition?
How bad are the command line steps, really?"

"How would one-click install  play nice with homebrew/macports/whatever the
heck the person is already using?"

"What benefit does the open source project get from non-developers
installing Apostrophe at this stage?"

The importance of these questions is illustrated by the fact that when I
wrote the original one-command installer, everybody kind of went... "huh."
Because there isn't a use for it. There's no story to tell yet around what
a person who can't set up homebrew wants from Apostrophe.

None of these really have good answers yet but they are great to think
about.

We've had long talks about this as a group internally but it's good to
discuss it in github too.

On Sat, Aug 1, 2015 at 1:49 PM, benirose <notifications@github.com> wrote:

> Tom, can you include in the error "Do you have imagemagick or imagecrunch
> installed?" to make it super obvious?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/320#issuecomment-126941841>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment] 2015-08-01 18:10
(0vermind, I should mention that I'm not suggesting you're a "person who
can't install homebrew" at all! For you, a clearer message about what you
need to do is probably sufficient. But on a larger scale we're still
discussing what "one-click Apostrophe" means and what it accomplishes, as
you can see.)


On Sat, Aug 1, 2015 at 2:08 PM, Tom Boutell <tom@punkave.com> wrote:

> I put in this:
>
>       no image backend specified and neither "imagecrunch" nor the
> imagemagick utility "identify" found in PATH. Install imagemagick
>
> I went with "install imagemagick" because imagecrunch is rather obscure
> and most people aren't going to want to go find that little one-off of ours.
>
> * * *
>
> Some notes on the whole "one-click Apostrophe" discussion...
>
> I built it two years ago as part of an effort toward a one-line install
> command which worked, but was dropped because we really don't have a story
> to tell around that idea. Every time we get into it we reach questions like:
>
> "How would updates get installed later?"
>
> "What happens next if you install Apostrophe with 'one click'? Are you
> then dumped into the command-line world, or does it need a configuration UI
> like Drupal? Who will build and maintain that?"
>
> "Do we install xcode and homebrew for you? Can we even do the former? Or
> do we provide a starter kit of pre-built set of binaries and tell you to
> move to homebrew later if you are serious? How do people make that
> transition? How bad are the command line steps, really?"
>
> "How would one-click install  play nice with homebrew/macports/whatever
> the heck the person is already using?"
>
> "What benefit does the open source project get from non-developers
> installing Apostrophe at this stage?"
>
> The importance of these questions is illustrated by the fact that when I
> wrote the original one-command installer, everybody kind of went... "huh."
> Because there isn't a use for it. There's no story to tell yet around what
> a person who can't set up homebrew wants from Apostrophe.
>
> None of these really have good answers yet but they are great to think
> about.
>
> We've had long talks about this as a group internally but it's good to
> discuss it in github too.
>
> On Sat, Aug 1, 2015 at 1:49 PM, benirose <notifications@github.com> wrote:
>
>> Tom, can you include in the error "Do you have imagemagick or imagecrunch
>> installed?" to make it super obvious?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/punkave/apostrophe/issues/320#issuecomment-126941841>
>> .
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by benirose** [comment] 2015-08-01 22:51
Good thoughts Tom, glad they are documented here.

"There's no story to tell yet around what a person who can't set up homebrew wants from Apostrophe."

Agree whole heartedly at this point, but we do want to prep ourselves for the future as well. And we also want to put a fence up for those who can find their way around homebrew but just neglected to read the documentation.

**Comment by benirose** [comment] 2015-08-01 22:51
Whoops didn't meant to re-open!

**Comment by kylestetz** [comment] 2015-08-01 22:51
@0vermind, what kind of automated process are you imagining? Are there other projects out there that you think do automated installation well?

**Closed by benirose** 2015-08-01 22:51 UTC

**Comment by 0vermind** [comment] 2015-08-02 15:34
I think a lot of command or operations can be skipped with a more automated install process.
To me A web Installer should be fine, but making more complete the npm installation would be better.
p.s. Of course I've already installed imagemagic  but seems not to find it.
I also tried npm install or yum install imagemagick. What I need to do to install properly?

**Comment by boutell** [comment] 2015-08-02 20:16
Hooray!

**Comment by boutell** [comment] 2015-08-02 20:17
(More points to consider: 0vermind has CentOS/RedHat Linux. Other people might have Ubuntu/Debian, MacOS, Windows...)
