### ISSUE TITLE
unable to delete pages from the trash

### ISSUE THREAD

**Issue by LifeLockWWW** [punkave/apostrophe#789] opened 2017-01-10 22:23 UTC
If you delete a page and then try to delete that page from the trash using the reorganize menu.  

Then it says an error occurred.   and the page is not deleted. 

See error on attached screenshot 
<img width="1432" alt="screen shot 2017-01-10 at 2 21 31 pm" src="https://cloud.githubusercontent.com/assets/21042780/21827423/5ac4e294-d740-11e6-86dc-634d5d083499.png">

**Comment by LifeLockWWW** [comment] 2017-01-11 21:03
The implication is that - the same slug (URL) cannot be used unless the page is actually deleted from the trash.

**Comment by boutell** [comment] 2017-01-12 18:09
Effectively a duplicate of #385 (but that one was mislabeled as an 0.5 issue, I've corrected that). When a page moves to the trash its slug should change to avoid such conflicts.

**Comment by boutell** [comment] 2017-01-12 18:10
Closing as a duplicate (see #385 going forward).

**Closed by boutell** 2017-01-12 18:10 UTC
