### ISSUE TITLE
Error occurs intermittently when trying to save page settings

### ISSUE THREAD

**Issue by ksinton** [punkave/apostrophe#874] opened 2017-05-02 18:33 UTC
This is happing on our dev and production environments which are load balanced.

Most of the times the page settings work fine but about one in ten times the setting will just not save. 

I managed to get a screen shot of the Javascript console when this happened (see screen shot).

It is possible that this is caused by a network issue but.. even if that's the case im thinking it should fail gracefully and not crash. 

FYI  this started happening more recently and after we upgraded to a newer version of Apostrophe.

We are currently running 2.16.0
![screen shot 2017-04-28 at 5 09 41 pm](https://cloud.githubusercontent.com/assets/13780160/25633184/2805ff76-2f2b-11e7-9ada-bf6649a0d509.png)

**Comment by WorldWideWebb** [comment] 2017-05-02 20:41
Possibly related, but I'm also running into this. Screenshot:

https://www.dropbox.com/s/u6uoj7wa35d9f4e/Screenshot%202017-05-02%2013.40.14.png?dl=0

In my case, I'm trying to hide my parked search results page from navigation and get a javascript error every time (have tried it from different browsers and in different apostrophe environments - each running on different servers/workstations - same result on each).

**Comment by matmar10** [comment] 2017-05-27 11:30
I am seeing this too, but it's consistent. Every time I go into a sub-dialog flow from a main dialog I get this error when trying to close the page. (E.g. select an image for a field within a content type, then enter upload new an image).

**Comment by boutell** [comment] 2017-10-21 13:20
Closing this as I suspect it relates to multiple fixes since May. But feel free to reopen with instructions to reproduce the issue if it still exists for you.

**Closed by boutell** 2017-10-21 13:20 UTC
