### ISSUE TITLE
Can't include CKeditor plugin

### ISSUE THREAD

**Issue by pipinov** [punkave/apostrophe#277] opened 2015-07-01 05:17 UTC
Hi!
I can't include plugin for CKeditor.

I have next settings:
```javascript
'apostrophe-editor-2': {
	plugins: [
			{ name: 'panelbutton', path: '/editor/plugins/panelbutton/' },
			{ name: 'colorbutton', path: '/editor/plugins/colorbutton/' }
		]
	},
```

plugins folders is placed in public directory 'public/editor/plugins/.....'

in aposArea next options

```javascript
{{ aposArea(page, 'advt1', {controls: ['colorbutton']}) }}
```
but without results.

Help me please to decide this problem

Thanks!

**Comment by boutell** [comment] 2015-07-02 13:23
Are there any 404's in the browser indicating it's trying to load these
from anywhere?

On Wed, Jul 1, 2015 at 1:17 AM, Alexandr Pipinov <notifications@github.com>
wrote:

> Hi!
> I can't include plugin for CKeditor.
>
> I have next settings:
>
> 'apostrophe-editor-2': {
>     plugins: [
>             { name: 'panelbutton', path: '/editor/plugins/panelbutton/' },
>             { name: 'colorbutton', path: '/editor/plugins/colorbutton/' }
>         ]
>     },
>
> plugins folders is placed in public directory 'public/editor/plugins/.....'
>
> in aposArea next options
>
> {{ aposArea(page, 'advt1', {controls: ['colorbutton']}) }}
>
> but without results.
>
> Help me please to decide this problem
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/277>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jazz-ik** [comment] 2015-07-03 12:16
No, all resources is loaded. And more, for example, when I click an edit button I see white square with rounded corners with gray border. You can see it at screenshot. 
<img width="1434" alt="screenshot 2015-07-03 15 09 49" src="https://cloud.githubusercontent.com/assets/790368/8498968/0109dee6-2196-11e5-80e6-2fb80904d0f5.png">

**Comment by jth-** [comment] 2016-02-01 15:41
We're closing this issue since we haven't had any similar reports. If you find a way to reproduce this in the sandbox, let us know and we'll check it out.

**Closed by jth-** 2016-02-01 15:41 UTC
Labels: 0.5, question, review

**Comment by Megabyteceer** [comment] 2016-08-08 08:51
to enable text color button use {{ aposArea(page, 'advt1', {controls: ['TextColor']}) }}
