### ISSUE TITLE
[apostrophe-images] If an image that is chosen in the chooser is removed and another image is added, the same crop is used by default, even though the crop may not have yet been generated on the new image.

### ISSUE THREAD

**Issue by jth-** [punkave/apostrophe#572] opened 2016-05-31 19:17 UTC

**Comment by boutell** [comment] 2016-06-07 14:37
Jimmy, are you talking about an image file being replaced with a different JPEG (but it's the same piece)? Or about substituting a totally different piece and still getting the same crop? Thanks.

**Comment by jth-** [comment] 2016-06-07 14:42
I'm referring the latter, totally different piece. 

The former is likely also true, though that might actually be the proper behavior.

**Comment by boutell** [comment] 2016-06-13 18:24
1. Added image to slideshow
2. Clicked crop button
3. Cropped it to upper right corner
4. Saved. Observed it is cropped.
5. Clicked "edit images"
6. Clicked trash icon to remove first piece
7. Selected a different image/piece
8. Hit save
9. Observed that the crop is not reused.

Going to close this one for now since it doesn't seem to be reproducible
but let me know if you hit on a series of steps.

On Tue, Jun 7, 2016 at 10:42 AM, Jimmy Harrison <notifications@github.com>
wrote:

> I'm referring the latter, totally different piece.
>
> The former is likely also true, though that might actually be the proper
> behavior.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/punkave/apostrophe/issues/572#issuecomment-224302489>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAB9fT8Mp0GIyrPE1gzWnn5ePs4rcjKuks5qJYM4gaJpZM4Iq3Rb>
> .
>



-- 


*THOMAS BOUTELL, *SUPPORT LEAD
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Closed by boutell** 2016-06-13 18:24 UTC
Labels: 0.6+, bug

**Comment by jth-** [comment] 2016-06-28 13:33
Yeah, the conditions of this one were still a bit mysterious to me. I'll let you know if it comes back up and try to find more reproducible steps
